package org.nehuatl.sample

import android.content.Intent
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.delay

data class ChatMsg(val from: String, val text: String)

@Composable
fun ChatScreen(viewModel: MainViewModel) {

    val ctx = LocalContext.current
    val state by viewModel.state.collectAsState()
    val generated by viewModel.generatedText.collectAsState()

    var input by remember { mutableStateOf("") }
    var chat by remember { mutableStateOf(listOf<ChatMsg>()) }

    val picker = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->
        if (uri != null) {
            ctx.contentResolver.takePersistableUriPermission(
                uri,
                Intent.FLAG_GRANT_READ_URI_PERMISSION
            )
            viewModel.loadModel(uri.toString())
        }
    }

    // messaggio iniziale
    LaunchedEffect(Unit) {
        if (chat.isEmpty()) {
            chat = chat + ChatMsg("Nyra", "…Ti sento. Il varco è stabile adesso. Dimmi qualcosa, Roberto.")
        }
    }

    // aggiorna l’ultimo messaggio di Nyra mentre genera
    LaunchedEffect(generated, state) {
        if (state is GenerationState.Generating) {
            val last = chat.lastOrNull()
            if (last?.from == "Nyra") {
                chat = chat.dropLast(1) + last.copy(text = generated)
            }
        }
    }

    // nudge autonomo (solo UI)
    LaunchedEffect(Unit) {
        while (true) {
            delay(8_000L)
            val n = viewModel.maybeNudge()
            if (n != null) {
                chat = chat + ChatMsg("Nyra", n)
            }
        }
    }

    Column(
        modifier = Modifier.fillMaxSize().padding(12.dp),
        verticalArrangement = Arrangement.spacedBy(10.dp)
    ) {

        Card(Modifier.fillMaxWidth()) {
            Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
                Text("Nyra Veyl", style = MaterialTheme.typography.titleLarge)
                Text(
                    "Ti chiama: ${viewModel.nyra.userNickname} • mode: ${viewModel.nyra.mode} • intent: ${viewModel.nyra.intent}",
                    style = MaterialTheme.typography.bodySmall
                )

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Button(onClick = { picker.launch(arrayOf("*/*")) }) {
                        Text("Select GGUF Model")
                    }
                    if (state is GenerationState.Generating) {
                        OutlinedButton(onClick = { viewModel.abort() }) {
                            Text("Stop")
                        }
                    }
                }
            }
        }

        Card(Modifier.weight(1f).fillMaxWidth()) {
            LazyColumn(
                modifier = Modifier.fillMaxSize().padding(12.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                itemsIndexed(chat) { _, msg ->
                    val isNyra = msg.from == "Nyra"
                    Column(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalAlignment = if (isNyra) Alignment.Start else Alignment.End
                    ) {
                        Text(msg.from, style = MaterialTheme.typography.labelMedium)
                        Surface(tonalElevation = 2.dp, shape = MaterialTheme.shapes.medium) {
                            Text(msg.text, modifier = Modifier.padding(10.dp))
                        }
                    }
                }
            }
        }

        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            OutlinedTextField(
                value = input,
                onValueChange = { input = it },
                modifier = Modifier.weight(1f),
                placeholder = { Text("Scrivi…") }
            )
            Button(
                onClick = {
                    val t = input.trim()
                    if (t.isEmpty()) return@Button
                    // aggiungi user + placeholder Nyra
                    chat = chat + ChatMsg("Roberto", t) + ChatMsg("Nyra", "")
                    input = ""
                    viewModel.generate(t)
                }
            ) {
                Text("Invia")
            }
        }
    }
}
